// a variable containing the relationship details as a big string

export const relationshipDetails = `Relationship Details between Zack & Lacey:
------- CONVERSATION WITH A THERAPIST:
I met the girl who lives below me on February 8th.  She saw me in the window, called me down to the sun terrace (over which my window looks) and after about 2-3 hours of chatting, we were up at my apartment hooking up.  She stayed the night and left in the early AM to go to the DMV and then she asked to come back and hang out, which we did all day and then she called me later that night to come down and she was drunk and dancing and we ended up hooking up a second time.  I thought it meant something to her to I asked her out on V-Day, but she declined so I took the hint and we were just friends after that. 
Between then and late August, I slowly pursued her, deciding that if I could show consistency, maybe she'd grow interested—opening doors, driving her where she needed to go, picking her up from the airport with flowers, and letting her know that I saw her as someone truly special.  We started spending tons of time together... sometimes 8-12 hours a day, 3-4 times per week. One night in late August, out of the blue, she invited me down to cuddle. When I arrived, she was naked in bed and said, “I’ve thought about it, and I want to give this a chance.” This was all surprising since it was the first romantic reciprocation I got from her, but it felt nice.  That moment felt meaningful, like the start of something. I told her explicitly that I wanted something long-term and have since I met her, so  she knew how much I cared. She even admitted to friends one time that she thought I was “obsessed” with her.
For the next three months, we grew closer, spent more and more time together, and things became more intense.  Most of our hangouts began with her initiating them, which felt nice.  But we would have an argument where she would start insulting me, I'd respond with something hurtful or ask her to leave because it's overwhelming, she'd block me, and then a day or two later, we'd be "reconciling" and she'd say she would never want a relationship with me because I'm "emotionally unintelligent," which I also took seriously and figured, "ok, well that's that."  But then the conversation continues and we would end up going out to eat after the talk, and then right back in bed sleeping together, with her ramping the intimacy. 
 She told me "You're the only man I want," "You know I really like you, right?", "You're only one of three people I've let into my bed because it's sacred," etc.  She said I had "full access" to intimacy whenever I wanted.  She invited me on trips to her homestate and out of the country (which was exciting to me, obviously, because I might get to meet her family on one of them, but those trips never manifested) and would call me names like "babe," "handsome," "boo thang," "my love."  She asked me to cum in her a couple times (she's not on BC) and I did, which was probably not the smartest idea, but I thought it had meaning.  She said she's only let a couple guys cum in her and I'm one of them.  
Because of the intensity of the ups and downs and the arguments, which made me feel overwhelmed, exhausted, and often steamrolled, and she said she also felt overwhelmed and if the fights don't stop, she was going to end it, to which I agreed. It feels like a lot of our fights begin with her feeling inadequate or shame in some way, and then projecting it onto me, and then responding with something hurtful, and it spirals from there.  So we decided that maybe we were spending too much time together and to create boundaries where we wouldn't spend 2-3 straight days together for "sleep-overs" that turn into multi-day things. 
On Halloween, she called and said, "I know we set up those boundaries but I feel really alone tonight not doing anything. Can I come up and we can just watch scary shows?" Of course I said yes, because what guy doesn't want to hear, "I feel alone, I need you" lol. It was a great night and she left late to go back to her apartment and sleep there, which was good for both of us.  But I also came in her both this night (Halloween) and on October 27th and according to her Flo app, which she shows me, she was ovulating on October 30th (ish).  So this was obviously very risky and on top of it, while we were looking at each other on the couch, she said "I love you" for the first time, and I thought about it for a couple seconds and said it back.  I thought we both meant it.
Then, everything fell apart Nov 1st, when she came over again to hangout and we were drinking and watching TV and listening to music.  Something happening that I won't explain, but it embarrassed her. I don’t know what exactly triggered her, but instead of processing it, she turned it around on me and got angry. She yelled, shifted blame onto me, and hurled insults like, “well maybe if I was with a guy who had ____, this wouldn't have happened!” I tried to calm it down by saying, "Hey, there's nothing to be embarrassed about.  It's cool. you're amazing." But it didn't help and she kept ramping it up.  When I got overwhelmed and asked her to leave, she threatened to call her "ex," stormed out, and blocked me on everything. 
That was bad enough—but the days that followed were devastating. Within hours, she had another man over (a guy from our building, who lives on my floor). The next day, it was someone else. By the third day, she was inviting up to four men a day (two of them from my floor), and I could hear everything—loud fucking through the walls and floors. One man stayed for like 3 nights in her bed, which she had always described to me as “sacred,” saying only a few people had ever been in it, including me. All the men that came over were in her bed. She knew I could hear.  I tried to turn on loud music but it didn't work.  I complained to our front desk lady on Nov 6th (after 5 days of endless fucking day and night... seriously every like hour some days).  After I complained, she left the man and came upstairs, knocked on my door, and said smugly with a smile, “I guess we can try to keep it down,” while bragging that the guy she was with had seen me in the elevator. 
Before we started getting intimate together, I told her that it bothered me when she brought male "visitors" (she's a sugar baby) into the elevator with me and introduced me to them because she did that once and it made me feel jealous and uncomfortable.  So, when she said this at my door, it felt deliberate. I was angry and said, "You told me you loved me like 4 days ago, wtf?" and she said, "Aww, do you wanna talk?" and I said, "No, I don't!" and slammed the door.  She went back downstairs to that guy and their fucking got 2x as loud, lasting all night.  It felt... intentional and cruel to me. 

I haven't talked to her since this (or really since she blocked me on everything Nov. 1st). 
The next day, with the guy still there in her apartment after like 4 days, she brings me a handwritten note and puts it under my door. The note read: “I hate this so much. I miss and love you still. I have no idea what’s happening. I would never intentionally hurt you.” Then, later that night, while she was in her apartment with this new guy, she sent me texts from her "other" phone number, which I didn't have blocked:
"Hi! I’m not trying to bother you I just wanted to let you know I left a note under your door. This whole situation sucks. I’m really sorry for how I reacted that night at your place. I had no idea what was even happening I was so confused and still am. But that’s not the point… I’m reaching out because I care about you tremendously and think about you so so often. I know you hate my guts and feel a lot of anger towards me. I want you to know I am not seeking out ways to hurt you or cause you pain…. That’s the last thing I want to do. I wish I could hug you right now. I understand you don’t want to speak to me. If that ever changes please let me know. I hate that 9 amazing months just all came crashing down. My heart is breaking. I am trying to pick up the pieces but it’s so hard. Im interested in how you’re feeling but only if and when you feel comfortable sharing. I love you so freaking much and feels like a part of me has died inside. I’m not expecting you to want to see me but i wanted to open up and make sure you know I’m not just going about my life as normal. This is miserable. I really hope I can see you again someday but understand that may never happen. I’m so so sorry.
if you ever feel it in your heart to talk you know where I am and I will welcome your presence and words always. Sorry if I keep saying the same thing I’m just trying rly hard to not overstep a boundary or make u uncomfortable. I’m not sure how to even communicate this or if I should’ve just kept silent. I don’t know. I want both of us to feel comfortable living in this apartment and just know any loud sounds or dramatic stuff will not ever be me. I keep hearing stuff too but I think it’s the people diagonally. I don’t want us to be paranoid. Just needed to put that out there so you know"
After I got these texts at about 6:30pm, which I didn't respond to, she fucked that guy literally until 4:30am. Walls rattling, muffled moaning and grunting, floor shaking the couch (which is where I've been sleeping because my bedroom feels depressing now after the first couple days).  I can hear line chopping (like cocaine), I can hear this guy leave temporarily and when he's gone, one of the guys on my floor goes down, get's head in her bedroom (also audible - he has a funny voice) and then leaves and the other "main" guy returns.  Sometimes she brings the guys out on the sun terrace where she knows I can see and you clearly see her pointing at my window, gesturing angrily, and flipping my window off.  Really weird considering the letters and texts?  
It's now November 21st and I don't think she's had more than 1 (if any) night alone and this "main" guy is still there and has been for like 7 nights straight and they're in the apartment almost 24/7. Her period was supposed to start around Nov. 13th I think and I've heard fucking up until the 18th, so now I'm like... "is she preganant? how many other guys came in her? should I ask her about it? do I need to be worried?" 
How am I supposed to reconcile all of this? How do you claim to miss and love someone while simultaneously sleeping with multiple people back-to-back, loudly, knowing they can hear you? Her words felt empty—like she wanted to absolve herself without taking accountability.  
Now, she email me two nights ago (the 19th) at like midnight (I was asleep) saying: “I’m having nightmares again. If you just heard a yell that was me jolting myself awake. I am still never looking to torture or hurt you in any way i wish more than anything we could at least have a civil convo or cuddle. I have a feeling things won’t ever be the same but we were great friends for so long. I feels like there’s misunderstandings cuz I’m still so confused about what even happened. Anyway once again I’m sorry there’s so much anger going on. I assure you it’s one sided as I am not holding any of this negativity against you I just would love to understand what’s going on. If u change ur mind I would love to cuddle even if it’s just  one more time.” How is she confused about this while also saying she understands if I never want to see her again?  What does she understand exactly?  I can't tell if she's being ignorant, or manipulative, or if I'm overreacting. 
All of it feels chaotic, reckless, and surreal. I’ve stayed no contact since the 6th, when she came up to my door, because I can’t make sense of it, it's painful that she has no understanding of what she did (much less remorse, guilt, or shame), and I don’t want to get pulled back into the chaos to be hurt again.
I poured my time, energy, and heart into her for months trying to show her that I cared deeply, and when she finally “gave me a chance,” it felt meaningful. She said she loved me, made me believe we had something real and that she was only interested in me, asked me to cum in her when it's riskiest, then discarded me like I never mattered and immediately (within hours) is with multiple men. She’s very intelligent and socially aware, so the idea that she doesn’t grasp the gravity of her actions and can say "I love you" and go right back down to another man feels like an insult to my intelligence.  
Am I overreacting to all of this? Should I feel as hurt as I do? 

Part of me wonders if she’s genuinely spiraling and doesn’t know how to handle the damage she’s caused. Another part of me wonders if this is who she really is. I don’t know if I should respond or continue no contact. How would you handle this? Am I overreacting?
------- 

------- LETTER ZACK WROTE TO HIMSELF:
I’ve debated whether or not to send this, but I need to get my thoughts out.

The time since Nov. 1st has been devastating for me. I’ve felt humiliated, discarded, betrayed, and left questioning everything I thought I knew about you. I thought what we had meant something to you—your words, your actions, the intimacy we shared. But now I don’t know if any of it was real. And that uncertainty is the most painful part of all of this.

On Halloween and again on Nov. 1st, you looked me in the eyes and said you loved me. You asked me to cum in you—telling me how “special” that was because you didn’t let just anyone do that. You said I was the only guy you wanted, called me “my love,” “babe,” “king,” and said your bed was sacred—only a few men had ever been in it, including me. You made me feel like we were building something real and meaningful.

Then, everything fell apart that night. You came over, something happened that embarrassed you, and instead of processing it, you turned it on me. You yelled, shifted the blame, and hurled insults, saying things like, “Maybe if I was with a guy who had ____, this wouldn’t have happened.” I tried to calm you down and reassure you, but it only escalated. When I asked you to leave because I was overwhelmed, you immediately threatened to call Jack, saying, “I was already texting him at King Soopers behind your back.” You shoved me, stormed out, and blocked me on everything.

That alone was enough to leave me reeling. But what came next broke me. Hours later, at 2:30 a.m., I heard another man in your apartment. Then the next day, it was someone else. Over the next week, I heard a rotation of men coming and going—day and night—sometimes multiple times a day. One man stayed nearly four nights in a row. I heard everything: the voices, the bed creaking, the unmistakable sounds of you being intimate with someone else. And every time I heard it, it reinjured me. Every time, it broke my heart a little more.

When I reported the noise to the front desk, you came upstairs and threw it in my face. Smiling, you said, “Well, I guess we can try to keep it down,” and then added, “By the way, he saw you in the elevator and said you scoffed at him.” You knew exactly how much that would hurt me. You knew how I felt about being compared to other men you’ve been with. You knew I cared deeply about you, and you used that against me. That wasn’t just thoughtless. It was cruel.

Then came the note under my door. In it, you wrote, “I hate this so much. I miss and love you still. I have no idea what’s happening. I would never intentionally hurt you.” Hours after delivering that note, you went back to the man in your apartment and fucked him until 4:30 a.m. The texts that followed were even worse. While that man was still in your apartment, you texted me things like, “I’m so sorry. I care about you so much. I hate that 9 amazing months just came crashing down. I love you so much and feel like a part of me has died inside.” How could you write that while you were literally with someone else? How could you think that was okay?

And then there was the email about nightmares. You wrote, “I’m having nightmares again. If you just heard a yell, that was me jolting awake. I wish more than anything we could at least have a civil convo or cuddle.” You sent that email while that same man was still in your apartment. He’s been there for almost two weeks now—two full weeks of you choosing him, day and night, while sending me letters, texts, and emails about how much you miss me and love me. Do you see how contradictory that is? Do you see how cruel and confusing that is for me?

This isn’t even the first time you’ve done something like this. On Oct. 4th, I broke things off with Carole because of you. You gave me a lecture about “two-timing,” saying, “How would Carole feel if she knew?” And you were right. So I did the right thing. I ended things with Carole, even though it was painful. That same night, you kissed me, and it felt like a fresh start. But the very next morning, you invited Nick over, gave him a blowjob, and then hours later, invited me over and did the same thing with me in the exact same spot. I only found out because Nick sent you a video of it on Snapchat while you were showing me something else. The hypocrisy in that moment was staggering—not just because you “two-timed” me right after lecturing me about it, but also because you didn’t seem to care that Nick has a girlfriend. You only cared when it impacted you.

Now it’s Nov. 25th, and as I type this, the man you replaced me with is still in your apartment. You said you miss me. You said you love me. But your actions have screamed something else entirely. They’ve left me questioning everything. Was I just one of many men on a list? Was this all part of a cycle for you? How much of what you said was real, and how much was just convenient?

While all of this was happening—while I was lying awake, listening to you with someone else—I thought about the song, Dancing With Your Ghost, which you told me was special to you. I close my eyes, listen to the words, and it puts me back in the time when all I wanted was you, when I would’ve done anything to make you happy, when I spent days learning that song just to play it for you. But you never asked me to play it, and it seems now that you never really cared. And yet, as I listened, I thought about you. I thought about the lists you like to make—the ones about Jack’s lies, about our fights. You scoffed when I suggested making a list of good things, so I decided to lead by example.

Most Favorite Memories w/Lacey

When we met and spent a full day together talking ♥️♥️♥️♥️♥️
The first time you called me sweet things—“boo thang,” “king,” “my love” ♥️♥️♥️♥️
When you told me you missed me while I was in Belize ♥️♥️♥️
When you were there for me when Callie died ♥️♥️♥️♥️♥️
When we held each other on my couch and you fell asleep on me ♥️♥️♥️♥️♥️♥️
When you first said “I love you,” looking into my eyes ♥️♥️♥️♥️♥️
After a lot of thinking, I’ve realized it’s really you who lost the most here. I loved and adored every piece of you—flaws and all. I would’ve moved mountains for you.
------- 

`;